const collection = [
  {
    id: 1,
    brand: "Jack & Danny",
    model: "D160S",
    desc: "lorem ipsum",
    img: "./img/guitar1.png",
    value: 7800,
    isNotBelong: true,
  },
  {
    id: 2,
    brand: "Paramount",
    model: "F-550BCEQN",
    desc: "lorem ipsum",
    img: "./img/guitar2.png",
    value: 3100,
    isNotBelong: true,
  },
  {
    id: 3,
    brand: "Mclorence",
    model: "MC138",
    desc: "lorem ipsum",
    img: "./img/guitar3.png",
    value: 4000,
    isNotBelong: true,
  },
  {
    id: 4,
    brand: "Ephiphone",
    model: "Special II",
    desc: "lorem ipsum",
    img: "./img/guitar4.png",
    value: 6300,
    isNotBelong: true,
  },
  {
    id: 5,
    brand: "Future",
    model: "SG-45",
    desc: "lorem ipsum",
    img: "./img/guitar5.png",
    value: 7000,
    isNotBelong: true,
  },
  {
    id: 6,
    brand: "Gibson",
    model: "Les Paul Standard '50s",
    desc: "lorem ipsum",
    img: "./img/guitar6.png",
    value: 85000,
    isNotBelong: false,
  },
  {
    id: 7,
    brand: "Fender",
    model: "Stratocaster American Original '50s",
    desc: "lorem ipsum",
    img: "./img/guitar7.png",
    value: 72000,
    isNotBelong: false,
  },
  {
    id: 8,
    brand: "Maison",
    model: "LP38",
    desc: "lorem ipsum",
    img: "./img/guitar8.png",
    value: 12000,
    isNotBelong: true,
  },
  {
    id: 9,
    brand: "Gibson",
    model: "Les Paul Gothic Morte",
    desc: "lorem ipsum",
    img: "./img/guitar9.png",
    value: 40000,
    isNotBelong: false,
  },
  {
    id: 10,
    brand: "Fender",
    model: 'Telecaster "3xbun" Signature',
    desc: "lorem ipsum",
    img: "./img/guitar10.png",
    value: 80000,
    isNotBelong: false,
  },
  {
    id: 11,
    brand: "Fender",
    model: 'Telecaster "Jim Root" Signature',
    desc: "lorem ipsum",
    img: "./img/guitar11.png",
    value: 47000,
    isNotBelong: true,
  },
  {
    id: 12,
    brand: "Gibson",
    model: 'SG 2013 "The Great Wave"',
    desc: "lorem ipsum",
    img: "./img/guitar12.png",
    value: 24000,
    isNotBelong: false,
  },
  {
    id: 13,
    brand: "Paramount",
    model: 'Flying V "Ouija Board"',
    desc: "lorem ipsum",
    img: "./img/guitar13.png",
    value: 8000,
    isNotBelong: false,
  },
  {
    id: 14,
    brand: "Gibson",
    model: "Les Paul Signature T Gold Series",
    desc: "lorem ipsum",
    img: "./img/guitar14.png",
    value: 58000,
    isNotBelong: false,
  },
  {
    id: 15,
    brand: "Spear",
    model: "RD-W",
    desc: "lorem ipsum",
    img: "./img/guitar15.png",
    value: 8500,
    isNotBelong: false,
  },
  {
    id: 16,
    brand: "Fender",
    model: "Stratocaster Master Build Jason Smith",
    desc: "lorem ipsum",
    img: "./img/guitar16.png",
    value: 92000,
    isNotBelong: false,
  },
];
